# Autogenerated by devscripts/update-version.py

__version__ = '2025.03.12.194726'

RELEASE_GIT_HEAD = '05c8023a27dd37c49163c0498bf98e3e3c1cb4b9'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'sudospaes/yt-dlp'

ORIGIN = 'sudospaes/yt-dlp'

_pkg_version = '2025.03.12.194726'
