# Autogenerated by devscripts/update-version.py

__version__ = '2025.03.15.124000'

RELEASE_GIT_HEAD = '4432a9390c79253ac830702b226d2e558b636725'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'sudospaes/yt-dlp'

ORIGIN = 'sudospaes/yt-dlp'

_pkg_version = '2025.03.15.124000'
